# 网站设置
title: "Chans"
description: "Leadership, engineering and product"
author: "chans"
email: "jiangsc2024@163.com"
url: "https://chanslights.github.io"
baseurl: "/blog"

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai

# Kramdown设置
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - start.sh
  - start.bat

# 集合设置
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# 默认值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# SEO 设置
lang: zh-CN
locale: zh_CN

# 社交媒体链接
social:
  twitter: "yourusername"
  github: "yourusername"
  linkedin: "yourusername" 