# Site settings
title: "我的博客"
author: "我的名字"
tagline: "思考，创作，分享"
description: "一个专注于技术分享与思考的个人博客"
email: your-email@example.com
url: "https://chanslights.github.io"
baseurl: "/blog"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CHANGELOG.md
  - start.sh
  - start.bat

# Sass
sass:
  style: compressed
  sass_dir: assets/css

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"

# SEO
twitter:
  username: your-twitter
  card: summary

social:
  name: 我的名字
  links:
    - https://github.com/chanslights
    - https://twitter.com/your-twitter 